services:
  app:
    image: ${DOCKER_USERNAME}/mait-dev-app:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JPA_DDL_AUTO=${JPA_DDL_AUTO}
    depends_on:
      - redis
    networks:
      - mait-network

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mait-network

volumes:
  redis-data:

networks:
  mait-network:
    driver: bridge