spring:
  config:
    import: classpath:variables/variable-dev.yml

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://localhost:3000/login/oauth2/code/google"